### ISSUE TITLE
ECML missing

### ISSUE THREAD

**Issue by giuseppec** [lucjaulmes/cfp-timeline#4]
Although you seem to have listed the acronym ECML (in ggs.csv) and ECML PKDD (in core.csv), the conference does not show up in the website. I guess it's because of the different acronyms? Maybe you can fix this and add a check to see if there are other conferences that are not showing up just because of different acronyms.

**Comment by lucjaulmes** [comment]
The mismatch in acronyms is between wiki-cfp (which has `ECML-PKDD`), and both sources (which have `ECML` and `ECML PKDD` as you noted). I can’t even fork the cfp to change the acronym to `ECML PKDD` to fix things in the short-term as that hack only works for cfp pages not search result pages.

Currently acronyms are matched exactly (case insensitively), but there seems to be some variability coming from conferences merging and increasing use of non-alphanumeric characters (spaces, `/`, `-`) which are then used inconsistently (as nobody remembers the correct characters I guess).

More annoyingly:
- it seems from the ECML example that `ECML PKDD` and `ECMLPKDD` are used interchangeably on the conference website, and while I think we can match exact words, matching prefixes fo acronyms will likely yield way too many incorrect matches. (This case is already one of the hardcoded acronym fixes, `Euro-Par` vs. `EuroPar`.)
- differing acronyms should probably also be accounted for when merging the various conference listings

**Comment by lucjaulmes** [comment]
Should be good now:

https://lucjaulmes.github.io/cfp-timeline/#conf=ECML%20PKDD
